path: /apps/RetroBlockGame3D_Data # Directory to the app. NOTE: It's the path in docker. EX: /apps/Diablo II
appFile: RetroBlockGame3D.exe # File Name of the app in the directory
windowTitle: RetroBlockGame3D # Window Title: not to show, it's the substring of title to help specify the running program in OS
pageTitle: "RetroBlockGame3D" # Page Title: To display on webpage
appName: RetroBlockGame3D # App name: to show in discovery
appMode: collaborative # app mode: collaborative/single (ex. collaborative: multiple user using same game session)
hasChat: true # Turn on chat
hardwareKey: true # Some game using DirectX needs hardward key. Turn this flag on to receive the input
gpuAccelerated: true # GPU acceleration with VirtualGL to replace Software Rendering with XVFB. Better performance
